### ISSUE TITLE
Trailing New Line

### ISSUE THREAD

**Issue by leehambley** [damien/rack-pretty_json#1]
Do you think it's wise to include a trailing newline in the prettified JSON responses? I'm seeing outputs such as:

``` text
< HTTP/1.1 422 Unprocessable Entity
< Content-Type: application/json; charset=utf-8
< Cache-Control: no-cache
< X-Request-Id: d614a89cca3c49a625f716c735eb02a9
< X-Runtime: 0.226025
< Transfer-Encoding: chunked
<
{
  "errors": {
    "sports": [
      "translation missing: en.errors.at_least_one"
    ],
    "email": [
      "can't be blank"
    ],
    "password_digest": [
      "can't be blank"
    ]
  }
* Connection #0 to host localhost left intact
}* Closing connection #0
```

And naturally enough would prefer that the response included a trailing new line.

**Comment by leehambley** [comment]
Clarification: I'm more than happy to add this if you would be interested in pulling that change.

**Comment by damien** [comment]
Hey Lee!

By all means, feel free to submit a patch! This seems perfectly reasonable to me. If you don't have time to add it in I'll probably address this issue myself within the next day or two.

**Comment by leehambley** [comment]
https://gist.github.com/ab2a0d49e5623faf7ec8 Implemented as a separate middleware /cc @ralph

**Comment by damien** [comment]
Forgot to close this! It's been fixed! Thanks again for the help!
